import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Nav from "./components/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar */}
        <Nav />

        {/* พื้นหลังขาว แล้วกล่องกลางสีฟ้า */}
        <div className="mt-6 bg-white min-h-screen flex flex-col">
          
          <div className="mt-2 bg-blue-100 px-4 md:px-8 mx-auto max-w-screen-lg flex-1 w-full">
            {children}
          </div>

        </div>

        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}